# -- Site Configuration --
theme = "terminal"

# baseURL = "https://matthewtwarren.github.io/"
defaultContentLanguage = "en"

pagination.pagerSize = 5

enableRobotsTXT = true
paperSize = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]
