languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Matt Warren"

[params]
  subtitle = "Data Scientist at The Institute of Cancer Research."
  menuMore = "More"
  readMore = "Read more"
  readOtherPosts = "Read other posts"
  newerPosts = "Newer posts"
  olderPosts = "Older posts"
  missingContentMessage = "Page not found..."
  missingBackButtonLabel = "Back to home page"
  minuteReadingTime = "min read"
  words = "words"

  [params.logo]
    logoText = "Matt Warren"
    logoHomeLink = "/"

  [[params.social]]
    name = "github"
    url = "https://github.com/matthewtwarren"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/matthewtwarren"

  [[params.social]]
    name = "x-twitter"
    url = "https://twitter.com/matthewthwarren"
