# -- Theme Options --
# Terminal theme parameters controlling layout and behaviour.

contentTypeName = "posts"
showMenuItems = 4
showLanguageSelector = false
fullWidthTheme = false
centerTheme = false
autoCover = true
showLastUpdated = false
readingTime = true
Toc = false
TocTitle = "Table of Contents"
dateFormat = "2 January 2006"

[twitter]
  # creator = ""
  # site = ""

[plausibleAnalytics]
  # domain = ""
  # event = ""
  # script = ""

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
